var companyNames = {
    "0000": "Ericsson Technology Licensing",
    "0001": "Nokia Mobile Phones",
    "0002": "Intel Corp.",
    "0003": "IBM Corp.",
    "0004": "Toshiba Corp.",
    "0005": "3Com",
    "0006": "Microsoft",
    "0007": "Lucent",
    "0008": "Motorola",
    "0009": "Infineon Technologies AG",
    "000a": "Cambridge Silicon Radio",
    "000b": "Silicon Wave",
    "000c": "Digianswer A/S",
    "000d": "Texas Instruments Inc.",
    "000e": "Ceva, Inc. (formerly Parthus Technologies, Inc.)",
    "000f": "Broadcom Corporation",
    "0010": "Mitel Semiconductor",
    "0011": "Widcomm, Inc",
    "0012": "Zeevo, Inc.",
    "0013": "Atmel Corporation",
    "0014": "Mitsubishi Electric Corporation",
    "0015": "RTX Telecom A/S",
    "0016": "KC Technology Inc.",
    "0017": "NewLogic",
    "0018": "Transilica, Inc.",
    "0019": "Rohde & Schwarz GmbH & Co. KG",
    "001a": "TTPCom Limited",
    "001b": "Signia Technologies, Inc.",
    "001c": "Conexant Systems Inc.",
    "001d": "Qualcomm",
    "001e": "Inventel",
    "001f": "AVM Berlin",
    "0020": "BandSpeed, Inc.",
    "0021": "Mansella Ltd",
    "0022": "NEC Corporation",
    "0023": "WavePlus Technology Co., Ltd.",
    "0024": "Alcatel",
    "0025": "NXP Semiconductors (formerly Philips Semiconductors)",
    "0026": "C Technologies",
    "0027": "Open Interface",
    "0028": "R F Micro Devices",
    "0029": "Hitachi Ltd",
    "002a": "Symbol Technologies, Inc.",
    "002b": "Tenovis",
    "002c": "Macronix International Co. Ltd.",
    "002d": "GCT Semiconductor",
    "002e": "Norwood Systems",
    "002f": "MewTel Technology Inc.",
    "0030": "ST Microelectronics",
    "0031": "Synopsis",
    "0032": "Red-M (Communications) Ltd",
    "0033": "Commil Ltd",
    "0034": "Computer Access Technology Corporation (CATC)",
    "0035": "Eclipse (HQ Espana) S.L.",
    "0036": "Renesas Electronics Corporation",
    "0037": "Mobilian Corporation",
    "0038": "Terax",
    "0039": "Integrated System Solution Corp.",
    "003a": "Matsushita Electric Industrial Co., Ltd.",
    "003b": "Gennum Corporation",
    "003c": "BlackBerry Limited (formerly Research In Motion)",
    "003d": "IPextreme, Inc.",
    "003e": "Systems and Chips, Inc.",
    "003f": "Bluetooth SIG, Inc.",
    "0040": "Seiko Epson Corporation",
    "0041": "Integrated Silicon Solution Taiwan, Inc.",
    "0042": "CONWISE Technology Corporation Ltd",
    "0043": "PARROT SA",
    "0044": "Socket Mobile",
    "0045": "Atheros Communications, Inc.",
    "0046": "MediaTek, Inc.",
    "0047": "Bluegiga",
    "0048": "Marvell Technology Group Ltd.",
    "0049": "3DSP Corporation",
    "004a": "Accel Semiconductor Ltd.",
    "004b": "Continental Automotive Systems",
    "004c": "Apple, Inc.",
    "004d": "Staccato Communications, Inc.",
    "004e": "Avago Technologies",
    "004f": "APT Licensing Ltd.",
    "0050": "SiRF Technology",
    "0051": "Tzero Technologies, Inc.",
    "0052": "J&M Corporation",
    "0053": "Free2move AB",
    "0054": "3DiJoy Corporation",
    "0055": "Plantronics, Inc.",
    "0056": "Sony Ericsson Mobile Communications",
    "0057": "Harman International Industries, Inc.",
    "0058": "Vizio, Inc.",
    "0059": "Nordic Semiconductor ASA",
    "005a": "EM Microelectronic-Marin SA",
    "005b": "Ralink Technology Corporation",
    "005c": "Belkin International, Inc.",
    "005d": "Realtek Semiconductor Corporation",
    "005e": "Stonestreet One, LLC",
    "005f": "Wicentric, Inc.",
    "0060": "RivieraWaves S.A.S",
    "0061": "RDA Microelectronics",
    "0062": "Gibson Guitars",
    "0063": "MiCommand Inc.",
    "0064": "Band XI International, LLC",
    "0065": "Hewlett-Packard Company",
    "0066": "9Solutions Oy",
    "0067": "GN Netcom A/S",
    "0068": "General Motors",
    "0069": "A&D Engineering, Inc.",
    "006a": "MindTree Ltd.",
    "006b": "Polar Electro OY",
    "006c": "Beautiful Enterprise Co., Ltd.",
    "006d": "BriarTek, Inc.",
    "006e": "Summit Data Communications, Inc.",
    "006f": "Sound ID",
    "0070": "Monster, LLC",
    "0071": "connectBlue AB",
    "0072": "ShangHai Super Smart Electronics Co. Ltd.",
    "0073": "Group Sense Ltd.",
    "0074": "Zomm, LLC ",
    "0075": "Samsung Electronics Co. Ltd.",
    "0076": "Creative Technology Ltd.",
    "0077": "Laird Technologies ",
    "0078": "Nike, Inc.",
    "0079": "lesswire AG",
    "007a": "MStar Semiconductor, Inc.",
    "007b": "Hanlynn Technologies",
    "007c": "A & R Cambridge",
    "007d": "Seers Technology Co. Ltd",
    "007e": "Sports Tracking Technologies Ltd.",
    "007f": "Autonet Mobile",
    "0080": "DeLorme Publishing Company, Inc.",
    "0081": "WuXi Vimicro",
    "0082": "Sennheiser Communications A/S",
    "0083": "TimeKeeping Systems, Inc.",
    "0084": "Ludus Helsinki Ltd.",
    "0085": "BlueRadios, Inc.",
    "0086": "equinox AG",
    "0087": "Garmin International, Inc.",
    "0088": "Ecotest",
    "0089": "GN ReSound A/S",
    "008a": "Jawbone",
    "008b": "Topcorn Positioning Systems, LLC",
    "008c": "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)​​",
    "008d": "Zscan Software",
    "008e": "Quintic Corp.",
    "008f": "Stollman E+V GmbH",
    "0090": "Funai Electric Co., Ltd.",
    "0091": "Advanced PANMOBIL Systems GmbH & Co. KG",
    "0092": "ThinkOptics, Inc.",
    "0093": "Universal Electronics, Inc.",
    "0094": "Airoha Technology Corp.",
    "0095": "NEC Lighting, Ltd.",
    "0096": "ODM Technology, Inc.",
    "0097": "ConnecteDevice Ltd.",
    "0098": "zer01.tv GmbH",
    "0099": "i.Tech Dynamic Global Distribution Ltd.",
    "009a": "Alpwise",
    "009b": "Jiangsu Toppower Automotive Electronics Co., Ltd.",
    "009c": "Colorfy, Inc.",
    "009d": "Geoforce Inc.",
    "009e": "Bose Corporation",
    "009f": "Suunto Oy",
    "00a0": "Kensington Computer Products Group",
    "00a1": "SR-Medizinelektronik",
    "00a2": "Vertu Corporation Limited",
    "00a3": "Meta Watch Ltd.",
    "00a4": "LINAK A/S",
    "00a5": "OTL Dynamics LLC",
    "00a6": "Panda Ocean Inc.",
    "00a7": "Visteon Corporation",
    "00a8": "ARP Devices Limited",
    "00a9": "Magneti Marelli S.p.A",
    "00aa": "CAEN RFID srl",
    "00ab": "Ingenieur-Systemgruppe Zahn GmbH",
    "00ac": "Green Throttle Games",
    "00ad": "Peter Systemtechnik GmbH",
    "00ae": "Omegawave Oy",
    "00af": "Cinetix",
    "00b0": "Passif Semiconductor Corp",
    "00b1": "Saris Cycling Group, Inc",
    "00b2": "Bekey A/S",
    "00b3": "Clarinox Technologies Pty. Ltd.",
    "00b4": "BDE Technology Co., Ltd.",
    "00b5": "Swirl Networks",
    "00b6": "Meso international",
    "00b7": "TreLab Ltd",
    "00b8": "Qualcomm Innovation Center, Inc. (QuIC)",
    "00b9": "Johnson Controls, Inc.",
    "00bA": "Starkey Laboratories Inc.",
    "00bb": "S-Power Electronics Limited",
    "00bc": "Ace Sensor Inc",
    "00bd": "Aplix Corporation",
    "00be": "AAMP of America",
    "00bf": "Stalmart Technology Limited",
    "00c0": "AMICCOM Electronics Corporation",
    "00c1": "Shenzhen Excelsecu Data Technology Co.,Ltd",
    "00c2": "Geneq Inc.",
    "00c3": "adidas AG",
    "00c4": "LG Electronics",
    "00c5": "Onset Computer Corporation",
    "00c6": "Selfly BV",
    "00c7": "Quuppa Oy.",
    "00c8": "GeLo Inc",
    "00c9": "Evluma",
    "00ca": "MC10",
    "00cb": "Binauric SE",
    "00cc": "Beats Electronics",
    "00cd": "Microchip Technology Inc.",
    "00ce": "Elgato Systems GmbH",
    "00cf": "ARCHOS SA",
    "00d0": "Dexcom, Inc.",
    "00d1": "Polar Electro Europe B.V.",
    "00d2": "Dialog Semiconductor B.V.",
    "00d3": "Taixingbang Technology (HK) Co,. LTD.",
    "00d4": "Kawantech",
    "00d5": "Austco Communication Systems",
    "00d6": "Timex Group USA, Inc.",
    "00d7": "Qualcomm Technologies, Inc.",
    "00d8": "Qualcomm Connected Experiences, Inc.",
    "00d9": "Voyetra Turtle Beach",
    "00da": "txtr GmbH",
    "00db": "Biosentronics",
    "00dc": "Procter & Gamble",
    "00dd": "Hosiden Corporation",
    "00de": "Muzik LLC",
    "00df": "Misfit Wearables Corp",
    "00e0": "Google",
    "00e1": "Danlers Ltd",
    "00e2": "Semilink Inc",
    "00e3": "inMusic Brands, Inc",
    "00e4": "L.S. Research Inc.",
    "00e5": "Eden Software Consultants Ltd.",
    "00e6": "Freshtemp",
    "00e7": "KS Technologies",
    "00e8": "ACTS Technologies",
    "00e9": "Vtrack Systems",
    "00ea": "Nielsen-Kellerman Company",
    "00eb": "Server Technology, Inc.",
    "00ec": "BioResearch Associates",
    "00ed": "Jolly Logic, LLC",
    "00ee": "Above Average Outcomes, Inc.",
    "00ef": "Bitsplitters GmbH",
    "00f0": "PayPal, Inc.",
    "00f1": "Witron Technology Limited",
    "00f2": "Aether Things Inc. (formerly Morse Project Inc.)",
    "00f3": "Kent Displays Inc.",
    "00f4": "Nautilus Inc.",
    "00f5": "Smartifier Oy",
    "00f6": "Elcometer Limited",
    "00f7": "VSN Technologies Inc.",
    "00f8": "AceUni Corp., Ltd.",
    "00f9": "StickNFind",
    "00fa": "Crystal Code AB",
    "00fb": "KOUKAAM a.s.",
    "00fc": "Delphi Corporation",
    "00fd": "ValenceTech Limited",
    "00fe": "Reserved",
    "00ff": "Typo Products, LLC",
    "0100": "TomTom International BV",
    "0101": "Fugoo, Inc",
    "0102": "Keiser Corporation",
    "0103": "Bang & Olufsen A/S",
    "0104": "PLUS Locations Systems Pty Ltd",
    "0105": "Ubiquitous Computing Technology Corporation",
    "0106": "Innovative Yachtter Solutions",
    "0107": "William Demant Holding A/S",
    "0108": "Chicony Electronics Co., Ltd.",
    "0109": "Atus BV",
    "010a": "Codegate Ltd.",
    "010b": "ERi, Inc.",
    "010c": "Transducers Direct, LLC",
    "010d": "Fujitsu Ten Limited",
    "010e": "Audi AG",
    "010f": "HiSilicon Technologies Co., Ltd.",
    "0110": "Nippon Seiki Co., Ltd.",
    "0111": "Steelseries ApS",
    "0112": "vyzybl Inc.",
    "0113": "Openbrain Technologies, Co., Ltd.",
    "0114": "Xensr",
    "0115": "e.solutions",
    "0116": "1OAK Technologies",
    "0117": "Wimoto Technologies Inc",
    "0118": "Radius Networks, Inc.",
    "0119": "Wize Technology Co., Ltd.",
    "011a": "Qualcomm Labs, Inc. ",
    "011b": "Aruba Networks",
    "011c": "Baidu",
    "011d": "Arendi AG",
    "011e": "Skoda Auto a.s.",
    "011f": "Volkswagon AG",
    "0120": "Porsche AG",
    "0121": "Sino Wealth Electronic Ltd.",
    "0122": "AirTurn, Inc.",
    "0123": "Kinsa, Inc.",
    "0124": "HID Global",
    "0125": "SEAT es",
    "0126": "Promethean Ltd.",
    "0127": "Salutica Allied Solutions",
    "0128": "GPSI Group Pty Ltd",
    "0129": "Nimble Devices Oy",
    "012a": "Changzhou Yongse Infotech Co., Ltd",
    "012b": "SportIQ",
    "012c": "TEMEC Instruments B.V.",
    "012d": "Sony Corporation",
    "012e": "ASSA ABLOY",
    "012f": "Clarion Co., Ltd.",
    "0130": "Warehouse Innovations",
    "0131": "Cypress Semiconductor Corporation",
    "0132": "MADS Inc",
    "0133": "Blue Maestro Limited",
    "0134": "Resolution Products, Inc.",
    "0135": "Airewear LLC",
    "0136": "Seed Labs, Inc. (formerly ETC sp. z.o.o.)",
    "0137": "Prestigio Plaza Ltd.",
    "0138": "NTEO Inc.",
    "0139": "Focus Systems Corporation",
    "013a": "Tencent Holdings Limited",
    "013b": "Allegion",
    "013c": "Murata Manufacuring Co., Ltd.",
    "013e": "Nod, Inc.",
    "013f": "B&B Manufacturing Company",
    "0140": "Alpine Electronics (China) Co., Ltd",
    "0141": "FedEx Services",
    "0142": "Grape Systems Inc.",
    "0143": "Bkon Connect",
    "0144": "Lintech GmbH",
    "0145": "Novatel Wireless",
    "0146": "Ciright",
    "0147": "Mighty Cast, Inc.",
    "0148": "Ambimat Electronics",
    "0149": "Perytons Ltd.",
    "014a": "Tivoli Audio, LLC",
    "014b": "Master Lock",
    "014c": "Mesh-Net Ltd",
    "014d": "Huizhou Desay SV Automotive CO., LTD.",
    "014e": "Tangerine, Inc.",
    "014f": "B&W Group Ltd.",
    "0150": "Pioneer Corporation",
    "0151": "OnBeep",
    "0152": "Vernier Software & Technology",
    "0153": "ROL Ergo",
    "0154": "Pebble Technology",
    "0155": "NETATMO",
    "0156": "Accumulate AB",
    "0157": "Anhui Huami Information Technology Co., Ltd.",
    "0158": "Inmite s.r.o.",
    "0159": "ChefSteps, Inc.",
    "015a": "micas AG",
    "015b": "Biomedical Research Ltd.",
    "015c": "Pitius Tec S.L.",
    "015d": "Estimote, Inc.",
    "015e": "Unikey Technologies, Inc.",
    "015f": "Timer Cap Co.",
    "0160": "AwoX",
    "0161": "yikes",
    "0162": "MADSGlobal NZ Ltd.",
    "0163": "PCH International",
    "0164": "Qingdao Yeelink Information Technology Co., Ltd.",
    "0165": "Milwaukee Tool (formerly Milwaukee Electric Tools)",
    "0166": "MISHIK Pte Ltd",
    "0167": "Bayer HealthCare",
    "0168": "Spicebox LLC",
    "0169": "emberlight",
    "016a": "Cooper-Atkins Corporation",
    "016b": "Qblinks",
    "016c": "MYSPHERA",
    "016d": "LifeScan Inc",
    "016e": "Volantic AB",
    "016f": "Podo Labs, Inc",
    "0170": "Roche Diabetes Care AG",
    "0171": "Amazon Fulfillment Service",
    "0172": "Connovate Technology Private Limited",
    "0173": "Kocomojo, LLC",
    "0174": "Everykey LLC",
    "0175": "Dynamic Controls",
    "0176": "SentriLock",
    "0177": "I-SYST inc.",
    "0178": "CASIO COMPUTER CO., LTD.",
    "0179": "LAPIS Semiconductor Co., Ltd.",
    "017a": "Telemonitor, Inc.",
    "017b": "taskit GmbH",
    "017c": "Daimler AG",
    "017d": "BatAndCat",
    "017e": "BluDotz Ltd",
    "017f": "XTel ApS",
    "0180": "Gigaset Communications GmbH",
    "0181": "Gecko Health Innovations, Inc.",
    "0182": "HOP Ubiquitous",
    "0183": "To Be Assigned",
    "0184": "Nectar",
    "0185": "bel'apps LLC",
    "0186": "CORE Lighting Ltd",
    "0187": "Seraphim Sense Ltd",
    "0188": "Unico RBC",
    "0189": "Physical Enterprises Inc.",
    "018a": "Able Trend Technology Limited",
    "018b": "Konica Minolta, Inc.",
    "018c": "Wilo SE",
    "018d": "Extron Design Services",
    "018e": "Fitbit, Inc.",
    "018f": "Fireflies Systems",
    "0190": "Intelletto Technologies Inc.",
    "0191": "FDK CORPORATION ",
    "0192": "Cloudleaf, Inc",
    "0193": "Maveric Automation LLC",
    "0194": "Acoustic Stream Corporation",
    "0195": "Zuli",
    "0196": "Paxton Access Ltd",
    "0197": "WiSilica Inc",
    "0198": "Vengit Limited",
    "0199": "SALTO SYSTEMS S.L.",
    "019a": "TRON Forum (formerly T-Engine Forum)",
    "019b": "CUBETECH s.r.o.",
    "019c": "Cokiya Incorporated",
    "019d": "CVS Health",
    "019e": "Ceruus",
    "019f": "Strainstall Ltd",
    "01a0": "Channel Enterprises (HK) Ltd.",
    "01a1": "FIAMM",
    "01a2": "GIGALANE.CO.,LTD",
    "01a3": "EROAD",
    "01a4": "Mine Safety Appliances",
    "01a5": "Icon Health and Fitness",
    "01a6": "Asandoo GmbH",
    "01a7": "ENERGOUS CORPORATION",
    "01a8": "Taobao",
    "01a9": "Canon Inc.",
    "01aa": "Geophysical Technology Inc.",
    "01ab": "Facebook, Inc.",
    "01ac": "Nipro Diagnostics, Inc.",
    "01ad": "FlightSafety International",
    "01ae": "Earlens Corporation",
    "01af": "Sunrise Micro Devices, Inc.",
    "01b0": "Star Micronics Co., Ltd.",
    "01b1": "Netizens Sp. z o.o.",
    "01b2": "Nymi Inc.",
    "01b3": "Nytec, Inc.",
    "01b4": "Trineo Sp. z o.o.",
    "01b5": "Nest Labs Inc.",
    "01b6": "LM Technologies Ltd",
    "01b7": "General Electric Company",
    "01b8": "i+D3 S.L.",
    "01b9": "HANA Micron",
    "01ba": "Stages Cycling LLC",
    "01bb": "Cochlear Bone Anchored Solutions AB",
    "01bc": "SenionLab AB",
    "01bd": "Syszone Co., Ltd",
    "01be": "Pulsate Mobile Ltd.",
    "01bf": "Hong Kong HunterSun Electronic Limited",
    "01c0": "pironex GmbH",
    "01c1": "BRADATECH Corp.",
    "01c2": "Transenergooil AG",
    "01c3": "Bunch",
    "01c4": "DME Microelectronics",
    "01c5": "Bitcraze AB",
    "01c6": "HASWARE Inc.",
    "01c7": "Abiogenix Inc.",
    "01c8": "Poly-Control ApS",
    "01c9": "Avi-on",
    "01ca": "Laerdal Medical AS",
    "01cb": "Fetch My Pet",
    "01cc": "Sam Labs Ltd.",
    "01cd": "Chengdu Synwing Technology Ltd",
    "01ce": "HOUWA SYSTEM DESIGN, k.k.",
    "01cf": "BSH",
    "01d0": "Primus Inter Pares Ltd",
    "01d1": "August",
    "01d2": "Gill Electronics",
    "01d3": "Sky Wave Design",
    "01d4": "Newlab S.r.l.",
    "01d5": "ELAD srl",
    "01d6": "G-wearables inc.",
    "01d7": "Squadrone Systems Inc.",
    "01d8": "Code Corporation",
    "01d9": "Savant Systems LLC",
    "01da": "Logitech International SA",
    "01db": "Innblue Consulting",
    "01dc": "iParking Ltd.",
    "01dd": "Koninklijke Philips Electronics N.V.",
    "01de": "Minelab Electronics Pty Limited",
    "01df": "Bison Group Ltd.",
    "01e0": "Widex A/S",
    "01e1": "Jolla Ltd",
    "01e2": "Lectronix, Inc.",
    "01e3": "Caterpillar Inc",
    "01e4": "Freedom Innovations",
    "01e5": "Dynamic Devices Ltd",
    "01e6": "Technology Solutions (UK) Ltd",
    "01e7": "IPS Group Inc.",
    "01e8": "STIR",
    "01e9": "Sano, Inc",
    "01ea": "Advanced Application Design, Inc.",
    "01eb": "AutoMap LLC",
    "01ec": "Spreadtrum Communications Shanghai Ltd",
    "01ed": "CuteCircuit LTD",
    "01ee": "Valeo Service",
    "01ef": "Fullpower Technologies, Inc.",
    "01f0": "KloudNation",
    "01f1": "Zebra Technologies Corporation",
    "01f2": "Itron, Inc.",
    "01f3": "The University of Tokyo",
    "01f4": "UTC Fire and Security",
    "01f5": "Cool Webthings Limited",
    "01f6": "DJO Global",
    "01f7": "Gelliner Limited",
    "01f8": "Anyka (Guangzhou) Microelectronics Technology Co, LTD",
    "01f9": "Medtronic, Inc.",
    "01fa": "Gozio, Inc.",
    "01fb": "Form Lifting, LLC",
    "01fc": "Wahoo Fitness, LLC",
    "01fd": "Kontakt Micro-Location Sp. z o.o.",
    "01fe": "Radio System Corporation",
    "01ff": "Freescale Semiconductor, Inc.",
    "0200": "Verifone Systems PTe Ltd. Taiwan Branch",
    "0201": "AR Timing",
    "0202": "Rigado LLC",
    "0203": "Kemppi Oy",
    "0204": "Tapcentive Inc.",
    "0205": "Smartbotics Inc.",
    "0206": "Otter Products, LLC",
    "0207": "STEMP Inc.",
    "0208": "LumiGeek LLC",
    "0209": "InvisionHeart Inc.",
    "020a": "Macnica Inc.",
    "020b": "Jaguar Land Rover Limited",
    "020c": "CoroWare Technologies, Inc",
    "020d": "Simplo Technology Co., LTD",
    "020e": "Omron Healthcare Co., LTD",
    "020f": "Comodule GMBH",
    "0210": "ikeGPS",
    "0211": "Telink Semiconductor Co. Ltd",
    "0212": "Interplan Co., Ltd",
    "0213": "Wyler AG",
    "0214": "IK Multimedia Production srl",
    "0215": "Lukoton Experience Oy",
    "0216": "MTI Ltd",
    "0217": "Tech4home, Lda",
    "0218": "Hiotech AB",
    "0219": "DOTT Limited",
    "021a": "Blue Speck Labs, LLC",
    "021b": "Cisco Systems Inc",
    "021c": "Mobicomm Inc",
    "021d": "Edamic",
    "021e": "Goodnet Ltd",
    "021f": "Luster Leaf Products Inc",
    "0220": "Manus Machina BV",
    "0221": "Mobiquity Networks Inc",
    "0222": "Praxis Dynamics",
    "0223": "Philip Morris Products S.A.",
    "0224": "Comarch SA",
    "0225": "Nestlé Nespresso S.A.",
    "0226": "Merlinia A/S",
    "0227": "LifeBEAM Technologies",
    "0228": "Twocanoes Labs, LLC",
    "0229": "Muoverti Limited",
    "022a": "Stamer Musikanlagen GMBH",
    "022b": "Tesla Motors",
    "022c": "Pharynks Corporation",
    "022d": "Lupine",
    "022e": "Siemens AG",
    "022f": "Huami (Shanghai) Culture Communication CO., LTD",
    "0230": "Foster Electric Company, Ltd",
    "0231": "ETA SA",
    "0232": "x-Senso Solutions Kft",
    "0233": "Shenzhen SuLong Communication Ltd",
    "0234": "FengFan (BeiJing) Technology Co, Ltd",
    "0235": "Qrio Inc",
    "0236": "Pitpatpet Ltd",
    "0237": "MSHeli s.r.l.",
    "0238": "Trakm8 Ltd",
    "0239": "JIN CO, Ltd",
    "023a": "Alatech Technology",
    "023b": "Beijing CarePulse Electronic Technology Co, Ltd",
    "023c": "Awarepoint",
    "023d": "ViCentra B.V.",
    "023e": "Raven Industries",
    "023f": "WaveWare Technologies",
    "0240": "Argenox Technologies",
    "0241": "Bragi GmbH",
    "0242": "16Lab Inc",
    "0243": "Masimo Corp",
    "0244": "Iotera Inc.",
    "0245": "Endress+Hauser",
    "0246": "ACKme Networks, Inc.",
    "0247": "FiftyThree Inc.",
    "0248": "Parker Hannifin Corp​",
    "0249": "Transcranial Ltd",
    "024a": "Uwatec AG",
    "024b": "Orlan LLC",
    "024c": "Blue Clover Devices",
    "024d": "M-Way Solutions GmbH",
    "024e": "Microtronics Engineering GmbH",
    "024f": "Schneider Schreibgeräte GmbH",
    "0250​": "Sapphire Circuits LLC",
    "0251": "Lumo Bodytech Inc.",
    "0252": "UKC Technosolution",
    "0253": "Xicato Inc.",
    "0254": "Playbrush",
    "0255": "Dai Nippon Printing Co., Ltd.",
    "0256": "G24 Power Limited",
    "0257": "AdBabble Local Commerce Inc.",
    "0258": "Devialet SA",
    "0259": "ALTYOR",
    "025a": "University of Applied Sciences Valais/Haute Ecole Valaisanne",
    "025b": "​Five Interactive, LLC dba Zendo",
    "025c": "NetEase (Hangzhou) Network co.Ltd.",
    "025d": "Lexmark International Inc.",
    "025e": "Fluke Corporation",
    "025f": "Yardarm Technologies​",
    "0260": "SensaRx",
    "0261": "SECVRE GmbH",
    "0262": "Glacial Ridge Technologies",
    "0263": "Identiv, Inc.",
    "0264​": "DDS, Inc.",
    "0265": "SMK Corporation",
    "0266": "Schawbel Technologies LLC",
    "0267": "XMI Systems SA",
    "0268": "Cerevo",
    "0269": "​Torrox GmbH & Co KG",
    "026a": "​Gemalto",
    "026b": "DEKA Research & Development Corp.​",
    "026c": "Domster Tadeusz Szydlowski",
    "026d": "Technogym SPA​",
    "026e": "FLEURBAEY BVBA",
    "026f": "Aptcode Solutions​",
    "0270": "LSI ADL Technology​",
    "0271": "Animas Corp",
    "0272": "Alps Electric Co., Ltd.",
    "0273": "​OCEASOFT",
    "0274": "Motsai Research",
    "0275": "Geotab",
    "0276": "E.G.O. Elektro-Geratebau GmbH",
    "0277": "​bewhere inc",
    "0278​": "Johnson Outdoors Inc",
    "0279": "Steute Schaltgerate GmbH & Co. KG",
    "027a": "Ekomini in​c.​",
    "027b": "​DEFA AS",
    "027c": "Aseptika Ltd",
    "027d": "HUAWEI Technologies Co., Ltd.",
    "027e": "HabitAware, LLC",
    "027f": "Ruwido Austria GmbH​",
    "0280": "ITEC corporation",
    "0281": "StoneL​",
    "0282​": "Sonova AG",
    "0283": "Maven Machines, Inc.",
    "0284": "Synapse Electronics",
    "0285​": "Standard Innovation Inc.",
    "0286": "RF Code, Inc.",
    "0287": "Wally Ventures S.L.",
    "0288": "Willowbank Electronics Ltd",
    "0289": "SK Telecom",
    "028a": "Jetro AS",
    "028b": "Code Gears LTD",
    "028c": "NANOLINK APS",
    "028d": "​IF, LLC",
    "028e": "RF Digital Corp",
    "028f": "Church & Dwight Co., Inc",
    "0290": "Multibit Oy​",
    "0291": "CliniCloud Inc​",
    "0292": "​SwiftSensors",
    "0293": "Blue Bite​​",
    "0294": "​ELIAS GmbH",
    "0295": "Sivantos GmbH",
    "0296": "Petzl​",
    "0297": "Storm Power ltd",
    "0298": "EISST Ltd​",
    "0299": "Inexess Technology Simma KG​",
    "029a": "​Currant, Inc.",
    "029b": "C2 Development, Inc.",
    "029c": "Blue Sky Scientific, LLC",
    "029d": "ALOTTAZS LABS, LLC",
    "029e": "Kupson spol. s r.o.",
    "029f": "Areus Engineering GmbH​",
    "02a0": "Impossible Camera GmbH",
    "02a1": "InventureTrack Systems​",
    "02a2": "​LockedUp",
    "02a3": "Itude",
    "02a4": "Pacific Lock Company",
    "02a5": "Tendyron Corporation",
    "02a6": "Robert Bosch GmbH",
    "02a7": "Illuxtron international B.V.",
    "02a8": "miSport Ltd.",
    "02a9": "Chargelib",
    "02aa": "​Doppler Lab",
    "02ab": "BBPOS Limited",
    "02ac": "RTB Elektronik GmbH & Co. KG​​",
    "02ad": "Rx Networks, Inc.",
    "02ae": "​WeatherFlow, Inc.",
    "02af": "Technicolor USA Inc.​",
    "02b0": "Bestechnic(Shanghai),Ltd",
    "02b1": "​Raden Inc",
    "02b2": "JouZen Oy",
    "02b3": "​​CLABER S.P.A.",
    "02b4": "Hyginex, Inc.",
    "02b5": "HANSHIN ELECTRIC RAILWAY CO.,LTD.",
    "02b6": "Schneider Electric",
    "02b7": "Oort Technologies LLC​",
    "02b8": "Chrono Therapeutics",
    "02b9​": "Rinnai Corporation",
    "02ba": "​Swissprime Technologies AG",
    "02bb": "Koha.,Co.Ltd",
    "02bc": "Genevac Ltd​",
    "02bd": "​Chemtronics",
    "02be": "Seguro Technology Sp. z o.o.",
    "02bf": "Redbird Flight Simulations",
    "02c0": "Dash Robotics",
    "02c1": "LINE Corporation​",
    "02c2": "​Guillemot Corporation",
    "02c3": "Techtronic Power Tools Technology Limited",
    "02c4": "Wilson Sporting Goods",
    "02c5": "Lenovo (Singapore) Pte Ltd.",
    "02c6": "Ayatan Sensors",
    "02c7": "Electronics Tomorrow Limited",
    "02c8": "VASCO Data Security International, Inc.",
    "02c9": "PayRange Inc.​",
    "02ca": "ABOV ​Semiconductor",
    "02cb": "​AINA-Wireless Inc.​",
    "02cc": "​Eijkelkamp Soil & Water",
    "02cd": "BMA ergonomics b.v.",
    "02ce": "​Teva Branded Pharmaceutical Products R&D, Inc.",
    "02cf": "Anima",
    "02d0": "3M",
    "02d1": "​Empatica Srl",
    "02d2": "​​Afero, Inc.",
    "02d3": "Powercast Corporation",
    "02d4": "Secuyou ApS",
    "02d5": "​OMRON Corporation",
    "02d6": "Send Solutions",
    "02d7": "​NIPPON SYSTEMWARE CO.,LTD.",
    "02d8": "Neosfar",
    "02d9": "Fliegl Agrartechnik GmbH",
    "02da": "​Gilvader​",
    "02db": "Digi International Inc (R)",
    "02dc": "DeWalch Technologies, Inc.",
    "02dd": "Flint Rehabilitation Devices, LLC",
    "02de": "​Samsung SDS Co., Ltd.",
    "02df": "Blur Product Development​",
    "02e0": "University of Michigan",
    "02e1": "Victron Energy BV​",
    "02e2": "​​NTT docomo",
    "02e3": "Carmanah Technologies Corp.​",
    "02e4": "​Bytestorm Ltd.",
    "02e5": "Espressif Incorporated",
    "02e6": "Unwire​",
    "02e7": "Connected Yard, Inc.",
    "02e8": "American Music Environments",
    "02e9": "Sensogram Technologies, Inc.",
    "02ea": "Fujitsu Limited",
    "02eb": "Ardic Technology",
    "02ec": "Delta Systems, Inc",
    "02ed": "HTC Corporation",
    "02ee": "Citizen Holdings Co., Ltd.",
    "02ef": "SMART-INNOVATION.inc",
    "02f0": "Blackrat Software",
    "02f1": "The Idea Cave, LLC",
    "02f2": "GoPro, Inc.",
    "02f3": "AuthAir, Inc",
    "02f4": "Vensi, Inc.",
    "02f5": "Indagem Tech LLC",
    "02f6": "Intemo Technologies",
    "02f7": "DreamVisions co., Ltd.",
    "02f8": "Runteq Oy Ltd",
    "02f9": "IMAGINATION TECHNOLOGIES LTD",
    "02fa": "CoSTAR Technologies",
    "02fb": "Clarius Mobile Health Corp.",
    "02fc": "Shanghai Frequen Microelectronics Co., Ltd.",
    "02fd": "Uwanna, Inc.",
    "02fe": "Lierda Science & Technology Group Co., Ltd.",
    "02ff": "Silicon Laboratories",
    "0300": "World Moto Inc.",
    "0301": "Giatec Scientific Inc.",
    "0302": "Loop Devices, Inc",
    "0303": "IACA electronique",
    "0304": "Martians Inc",
    "0305": "Swipp ApS",
    "0306": "Life Laboratory Inc.",
    "0307": "FUJI INDUSTRIAL CO.,LTD.",
    "0308": "Surefire, LLC",
    "0309": "Dolby Labs",
    "030a": "Ellisys",
    "030b": "Magnitude Lighting Converters",
    "030c": "Hilti AG",
    "030d": "Devdata S.r.l.",
    "030e": "Deviceworx",
    "030f": "Shortcut Labs",
    "0310": "SGL Italia S.r.l.",
    "0311": "PEEQ DATA",
    "0312": "Ducere Technologies Pvt Ltd",
    "0313": "DiveNav, Inc.",
    "0314": "RIIG AI Sp. z o.o.",
    "0315": "Thermo Fisher Scientific",
    "0316": "AG Measurematics Pvt. Ltd.",
    "0317": "CHUO Electronics CO., LTD.",
    "0318": "Aspenta International",
    "0319": "Eugster Frismag AG",
    "031a": "Amber wireless GmbH",
    "031b": "HQ Inc",
    "031c": "Lab Sensor Solutions",
    "031d": "Enterlab ApS",
    "031e": "Eyefi, Inc.",
    "031f": "MetaSystem S.p.A",
    "0320": "SONO ELECTRONICS. CO., LTD",
    "0321": "Jewelbots",
    "0322": "Compumedics Limited",
    "0323": "Rotor Bike Components",
    "0324": "Astro, Inc.",
    "0325": "Amotus Solutions",
    "0326": "Healthwear Technologies (Changzhou)Ltd",
    "0327": "Essex Electronics",
    "0328": "Grundfos A/S",
    "0329": "Eargo, Inc.",
    "032a": "Electronic Design Lab",
    "032b": "ESYLUX",
    "032c": "NIPPON SMT.CO.,Ltd",
    "032d": "BM innovations GmbH",
    "032e": "indoormap",
    "032f": "OttoQ Inc",
    "0330": "North Pole Engineering",
    "0331": "3flares Technologies Inc.",
    "0332": "Electrocompaniet A.S.",
    "0333": "Mul-T-Lock",
    "0334": "Corentium AS",
    "0335": "Enlighted Inc",
    "0336": "GISTIC",
    "0337": "AJP2 Holdings, LLC",
    "0338": "COBI GmbH",
    "0339": "Blue Sky Scientific, LLC",
    "033a": "Appception, Inc.",
    "033b": "Courtney Thorne Limited",
    "033c": "Virtuosys",
    "033d": "TPV Technology Limited",
    "033e": "Monitra SA",
    "033f": "Automation Components, Inc.",
    "0340": "Letsense s.r.l.",
    "0341": "Etesian Technologies LLC",
    "0342": "GERTEC BRASIL LTDA.",
    "0343": "Drekker Development Pty. Ltd.",
    "0344": "Whirl Inc",
    "0345": "Locus Positioning",
    "0346": "Acuity Brands Lighting, Inc",
    "0347": "Prevent Biometrics",
    "0348": "Arioneo",
    "0349": "VersaMe",
    "034a": "Vaddio",
    "034b": "Libratone A/S",
    "034c": "HM Electronics, Inc.",
    "034d": "TASER International, Inc.",
    "034e": "Safe Trust Inc.",
    "034f": "Heartland Payment Systems",
    "0350": "Bitstrata Systems Inc.",
    "0351": "Pieps GmbH",
    "0352": "iRiding(Xiamen)Technology Co.,Ltd.",
    "0353": "Alpha Audiotronics, Inc.",
    "0354": "TOPPAN FORMS CO.,LTD.",
    "0355": "Signma Designs, Inc.",
    "0356": "Spectrum Brands, Inc.",
    "0357": "Polymap Wireless",
    "0358": "MagniWare Ltd.",
    "0359": "Novotec Medical GmbH",
    "035a": "Medicom Innovation Partners a/s",
    "035b": "Matrix Inc.",
    "035c": "Eaton Corporation",
    "035d": "KYS",
    "035e": "Naya Health, Inc.",
    "035f": "Acromag",
    "0360": "Insulet Corporation",
    "0361": "Wellinks Inc.",
    "0362": "ON Semiconductor",
    "0363": "FREELAP SA",
    "0364": "Favero Electronics Srl",
    "0365": "BioMech Sensor LLC",
    "0366": "BOLTT Sports technologies Private limited",
    "0367": "Saphe International",
    "0368": "Metormote AB",
    "0369": "littleBits",
    "036a": "SetPoint Medical",
    "036b": "BRControls Products BV",
    "036c": "Zipcar",
    "036d": "AirBolt Pty Ltd",
    "036e": "KeepTruckin Inc",
    "036f": "Motiv, Inc.",
    "0370": "Wazombi Labs OU",
    "0371": "ORBCOMM",
    "0372": "Nixie Labs, Inc.",
    "0373": "AppNearMe Ltd",
    "0374": "Holman Industries",
    "0375": "Expain AS",
    "0376": "Electronic Temperature Instruments Ltd",
    "0377": "Plejd AB",
    "0378": "Propeller Health",
    "0379": "Shenzhen iMCO Electronic Technology Co., Ltd",
    "037a": "Algoria",
    "037b": "Apption Labs Inc.",
    "037c": "Cronologics Corporation",
    "037d": "MICRODIA Ltd.",
    "037e": "lulabytes S.L.",
    "037f": "Nestec S.A.",
    "0380": "LLC MEGA-F service",
    "0381": "Sharp Corporation",
    "0382": "Precision Outcomes Ltd",
    "0383": "Kronos Incorporated",
    "0384": "OCOSMOS Co., Ltd.",
    "0385": "Embedded Electronic Solutions Ltd. dba e2Solutions",
    "0386": "Aterica Inc.",
    "0387": "BluStor PMC, Inc.",
    "0388": "Kapsch TrafficCom AB",
    "0389": "ActiveBlu Corporation",
    "038a": "Kohler Mira Limited",
    "038b": "Noke",
    "038c": "Appion Inc.",
    "038d": "Resmed Ltd",
    "038e": "Crownstone B.V.",
    "038f": "Xiaomi Inc.",
    "0390": "INFOTECH s.r.o.",
    "0391": "Thingsquare AB",
    "0392": "T&D",
    "0393": "LAVAZZA S.p.A.",
    "0394": "Netclearance Systems, Inc.",
    "0395": "SDATAWAY",
    "0396": "BLOKS GmbH",
    "0397": "LEGO System A/S",
    "0398": "Thetatronics Ltd",
    "0399": "Nikon Corporation",
    "039a": "NeST",
    "039b": "South Silicon Valley Microelectronics",
    "039c": "ALE International",
    "039d": "CareView Communications, Inc.",
    "039e": "SchoolBoard Limited",
    "039f": "Molex Corporation",
    "03a0": "IVT Wireless Limited",
    "03a1": "Alpine Labs LLC",
    "03a2": "Candura Instruments",
    "03a3": "SmartMovt Technology Co., Ltd",
    "03a4": "Token Zero Ltd",
    "03a5": "ACE CAD Enterprise Co., Ltd. (ACECAD)",
    "03a6": "Medela, Inc",
    "03a7": "AeroScout",
    "03a8": "Esrille Inc.",
    "03a9": "THINKERLY SRL",
    "03aa": "Exon Sp. z o.o.",
    "03ab": "Meizu Technology Co., Ltd.",
    "03ac": "Smablo LTD",
    "03ad": "XiQ",
    "03ae": "Allswell Inc.",
    "03af": "Comm-N-Sense Corp DBA Verigo",
    "03b0": "VIBRADORM GmbH",
    "03b1": "Otodata Wireless Network Inc.",
    "03b2": "Propagation Systems Limited",
    "03b3": "Midwest Instruments & Controls",
    "03b4": "Alpha Nodus, inc.",
    "03b5": "petPOMM, Inc",
    "03b6": "Mattel",
    "03b7": "Airbly Inc.",
    "03b8": "A-Safe Limited",
    "03b9": "FREDERIQUE CONSTANT SA",
    "03ba": "Maxscend Microelectronics Company Limited",
    "03bb": "Aboot Diabetes Care",
    "03bc": "ASB Bank Ltd",
    "03bd": "amadas",
    "03be": "Applied Science, Inc.",
    "03bf": "iLumi Solutions Inc.",
    "03c0": "Arch Systems Inc.",
    "03c1": "Ember Technologies, Inc.",
    "03c2": "Snapchat Inc",
    "03c3": "Casambi Technologies Oy",
    "03c4": "Pico Technology Inc.",
    "03c5": "St. Jude Medical, Inc.",
    "03c6": "Intricon",
    "03c7": "Structural Health Systems, Inc.",
    "03c8": "Avvel International",
    "03c9": "Gallagher Group",
    "03ca": "In2things Automation Pvt. Ltd.",
    "03cb": "SYSDEV Srl",
    "03cc": "Vonkil Technologies Ltd",
    "03cd": "Wynd Technologies, Inc.",
    "03ce": "CONTRINEX S.A.",
    "03cf": "MIRA, Inc.",
    "03d0": "Watteam Ltd",
    "03d1": "Density Inc.",
    "03d2": "IOT Pot India Private Limited",
    "03d3": "Sigma Connectivity AB",
    "03d4": "PEG PEREGO SPA",
    "03d5": "Wyzelink Systems Inc.",
    "03d6": "Yota Devices LTD",
    "03d7": "FINSECUR",
    "03d8": "Zen-Me Labs Ltd",
    "03d9": "3IWare Co., Ltd.",
    "03da": "EnOcean GmbH",
    "03db": "Instabeat, Inc",
    "03dc": "Nima Labs",
    "03dd": "Andreas Stihl AG & Co. KG",
    "03de": "Nathan Rhoades LLC",
    "03df": "Grob Technologies, LLC",
    "03e0": "Actions (Zhuhai) Technology Co., Limited",
    "03e1": "SPD Development Company Ltd",
    "03e2": "Sensoan Oy",
    "03e3": "Qualcomm Life Inc",
    "03e4": "Chip-ing AG",
    "03e5": "ffly4u",
    "03e6": "IoT Instruments Oy",
    "03e7": "TRUE Fitness Technology",
    "03e8": "Reiner Kartengeraete GmbH & Co. KG.",
    "03e9": "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD.",
    "03ea": "Hello Inc.",
    "03eb": "Evollve Inc.",
    "03ec": "Jigowatts Inc.",
    "03ed": "BASIC MICRO.COM,INC.",
    "03ee": "CUBE TECHNOLOGIES",
    "03ef": "foolography GmbH",
    "03f0": "CLINK",
    "03f1": "Hestan Smart Cooking Inc.",
    "03f2": "WindowMaster A/S",
    "03f3": "Flowscape AB",
    "03f4": "PAL Technologies Ltd",
    "03f5": "WHERE, Inc.",
    "03f6": "Iton Technology Corp.",
    "03f7": "Owl Labs Inc.",
    "03f8": "Rockford Corp.",
    "03f9": "Becon Technologies Co.,Ltd.",
    "03fa": "Vyassoft Technologies Inc",
    "03fb": "Nox Medical",
    "03fc": "Kimberly-Clark",
    "03fd": "Trimble Navigation Ltd.",
    "03fe": "Littelfuse",
    "03ff": "Withings",
    "0400": "i-developer IT Beratung UG",
    "0401": "Relations Co., Ltd.",
    "0402": "Sears Holdings Corporation",
    "0403": "Gartner Electronic GmbH",
    "0404": "Authomate Inc",
    "0405": "Vertex International, Inc.",
    "0406": "Airtago",
    "0407": "Swiss Audio SA",
    "0408": "ToGetHome Inc.",
    "0409": "AXIS",
    "040a": "Openmatics",
    "040b": "Jana Care Inc.",
    "040c": "Senix Corporation",
    "040d": "NorthStar Battery Company, LLC",
    "040e": "SKF (U.K.) Limited",
    "040f": "CO-AX Technology, Inc.",
    "0410": "Fender Musical Instruments",
    "0411": "Luidia Inc",
    "0412": "SEFAM",
    "0413": "Wireless Cables Inc",
    "0414": "Lightning Protection International Pty Ltd",
    "0415": "Uber Technologies Inc",
    "0416": "SODA GmbH",
    "0417": "Fatigue Science",
    "0418": "Alpine Electronics Inc.",
    "0419": "Novalogy LTD",
    "041a": "Friday Labs Limited",
    "041b": "OrthoAccel Technologies",
    "041c": "WaterGuru, Inc.",
    "041d": "Benning Elektrotechnik und Electronik GmbH & Co. KG",
    "041e": "Dell Computer Corporation",
    "041f": "Kopin Corporation",
    "0420": "TecBakery GmbH",
    "0421": "Backbone Labs, Inc.",
    "0422": "DELSEY SA",
    "0423": "Chargifi Limited",
    "0424": "Trainesense Ltd.",
    "0425": "Unify Software and Solutions GmbH & Co. KG",
    "0426": "Husqvarna AB",
    "0427": "Focus fleet and fuel management inc",
    "0428": "SmallLoop, LLC",
    "0429": "Prolon Inc.",
    "042a": "BD Medical",
    "042b": "iMicroMed Incorporated",
    "042c": "Ticto N.V.",
    "042d": "Meshtech AS",
    "042e": "MemCachier Inc.",
    "042f": "Danfoss A/S",
    "0430": "SnapStyk Inc.",
    "0431": "Amyway Corporation",
    "0432": "Silk Labs, Inc.",
    "0433": "Pillsy Inc.",
    "0434": "Hatch Baby, Inc.",
    "0435": "Blocks Wearables Ltd.",
    "0436": "Drayson Technologies (Europe) Limited",
    "0437": "eBest IOT Inc.",
    "0438": "Helvar Ltd",
    "0439": "Radiance Technologies",
    "043a": "Nuheara Limited",
    "043b": "Appside co., ltd.",
    "043c": "DeLaval",
    "043d": "Coiler Corporation",
    "043e": "Thermomedics, Inc.",
    "043f": "Tentacle Sync GmbH",
    "0440": "Valencell, Inc.",
    "0441": "iProtoXi Oy",
    "0442": "SECOM CO., LTD.",
    "0443": "Tucker International LLC",
    "0444": "Metanate Limited",
    "0445": "Kobian Canada Inc.",
    "0446": "NETGEAR, Inc.",
    "0447": "Fabtronics Australia Pty Ltd",
    "0448": "Grand Centrix GmbH",
    "0449": "1UP USA.com llc",
    "044a": "SHIMANO INC.",
    "044b": "Nain Inc.",
    "044c": "LifeStyle Lock, LLC",
    "044d": "VEGA Grieshaber KG",
    "044e": "Xtrava Inc.",
    "044f": "TTS Tooltechnic Systems AG & Co. KG",
    "0450": "Teenage Engineering AB",
    "0451": "Tunstall Nordic AB",
    "0452": "Svep Design Center AB",
    "0453": "GreenPeak Technologies BV",
    "0454": "Sphinx Electronics GmbH & Co KG",
    "0455": "Atomation",
    "0456": "Nemik Consulting Inc",
    "0457": "RF INNOVATION",
    "0458": "Mini Solution Co., Ltd.",
    "0459": "Lumenetix, Inc",
    "045a": "2048450 Ontario Inc",
    "045b": "SPACEEK LTD",
    "045c": "Delta T Corporation",
    "045d": "Boston Scientific Corporation",
    "045e": "Nuviz, Inc.",
    "045f": "Real Time Automation, Inc.",
    "0460": "Kolibree",
    "0461": "vhf electronik GmbH",
    "0462": "Bonsai Systems GmbH",
    "0463": "Fathom Systems Inc.",
    "0464": "Bellman & Symfon",
    "0465": "International Forte Group LLC",
    "0466": "CycleLabs Solutions inc.",
    "0467": "Codenex Oy",
    "0468": "Kynesim Ltd",
    "0469": "Palago AB",
    "046a": "INSIGMA INC.",
    "046b": "PMD Solutions",
    "046c": "Qingdao Realtime Technology Co., Ltd.",
    "046d": "BEGA Gantenbrink-Leuchten KG",
    "046e": "Pambor Ltd.",
    "ffff": "(Reserved) Default Vendor ID"
};

module.exports.companyNames = companyNames;
