var companyNames = {
    "feff": "GN Netcom",
    "fefe": "GN ReSound A/S",
    "fefd": "Gimbal, Inc.",
    "fefc": "Gimbal, Inc.",
    "fefb": "Stollmann E+V GmbH",
    "fefa": "PayPal, Inc.",
    "fef9": "PayPal, Inc.",
    "fef8": "Aplix Corporation",
    "fef7": "Aplix Corporation",
    "fef6": "Wicentric, Inc.",
    "fef5": "Dialog Semiconductor GmbH",
    "fef4": "Google",
    "fef3": "Google",
    "fef2": "CSR",
    "fef1": "CSR",
    "fef0": "Intel",
    "feef": "Polar Electro Oy",
    "feee": "Polar Electro Oy",
    "feed": "Tile, Inc.",
    "feec": "Tile, Inc.",
    "feeb": "Swirl Networks, Inc.",
    "feea": "Swirl Networks, Inc.",
    "fedb": "Perka, Inc.",
    "feda": "ISSC Technologies Corporation",
    "fed9": "Pebble Technology Corporation",
    "fed8": "Google",
    "fee9": "Quintic Corp.",
    "fee8": "Quintic Corp.",
    "fee7": "Tencent Holdings Limited",
    "fee6": "Seed Labs, Inc.",
    "fee5": "Nordic Semiconductor ASA",
    "fee4": "Nordic Semiconductor ASA",
    "fee3": "Anki, Inc.",
    "fee2": "Anki, Inc.",
    "fee1": "Anhui Huami Information Technology Co.",
    "fee0": "Anhui Huami Information Technology Co.",
    "fedf": "Design SHIFT",
    "fede": "Coin, Inc.",
    "fedd": "Jawbone",
    "fedc": "Jawbone",
    "fed7": "Broadcom Corporation",
    "fed6": "Broadcom Corporation",
    "fed5": "Plantronics Inc.",
    "fed4": "Apple, Inc.",
    "fed3": "Apple, Inc.",
    "fed2": "Apple, Inc.",
    "fed1": "Apple, Inc.",
    "fed0": "Apple, Inc.",
    "fecf": "Apple, Inc.",
    "fece": "Apple, Inc.",
    "fecd": "Apple, Inc.",
    "fecc": "Apple, Inc.",
    "fecb": "Apple, Inc.",
    "feca": "Apple, Inc.",
    "fec9": "Apple, Inc.",
    "fec8": "Apple, Inc.",
    "fec7": "Apple, Inc.",
    "fec6": "Kocomojo, LLC",
    "fec5": "Realtek Semiconductor Corp.",
    "fec4": "PLUS Location Systems",
    "fec3": "360fly, Inc.",
    "fec2": "Blue Spark Technologies, Inc.",
    "fec1": "KDDI Corporation",
    "fec0": "KDDI Corporation",
    "febf": "Nod, Inc.",
    "febe": "Bose Corporation",
    "febd": "Clover Network, Inc.",
    "febc": "Dexcom, Inc.",
    "febb": "adafruit industries",
    "feba": "Tencent Holdings Limited",
    "feb9": "LG Electronics",
    "feb8": "Facebook, Inc.",
    "feb7": "Facebook, Inc.",
    "feb6": "Vencer Co, Ltd",
    "feb5": "WiSilica Inc.",
    "feb4": "WiSilica Inc.",
    "feb3": "Taobao",
    "feb2": "Microsoft Corporation",
    "feb1": "Electronics Tomorrow Limited",
    "feb0": "Nest Labs Inc.",
    "feaf": "Nest Labs Inc.",
    "feae": "Nokia Corporation",
    "fead": "Nokia Corporation",
    "feac": "Nokia Corporation",
    "feab": "Nokia Corporation",
    "feaa": "Google",
    "fea9": "Savant Systems LLC",
    "fea8": "Savant Systems LLC",
    "fea7": "UTC Fire and Security",
    "fea6": "GoPro, Inc.",
    "fea5": "GoPro, Inc.",
    "fea4": "Paxton Access Ltd",
    "fea3": "ITT Industries",
    "fea2": "Intrepid Control Systems, Inc.",
    "fea1": "Intrepid Control Systems, Inc.",
    "fea0": "Google",
    "fe9f": "Google",
    "fe9e": "Dialog Semiconductor B.V.",
    "fe9d": "Mobiquity Networks Inc",
    "fe9c": "GSI Laboratories, Inc.",
    "fe9b": "Samsara Networks, Inc",
    "fe9a": "Estimote",
    "fe99": "Currant, Inc.",
    "fe98": "Currant, Inc.",
    "fe97": "Tesla Motor Inc.",
    "fe96": "Tesla Motor Inc.",
    "fe95": "Xiaomi Inc.",
    "fe94": "OttoQ Inc.",
    "fe93": "OttoQ Inc.",
    "fe92": "Jarden Safety & Security",
    "fe91": "Shanghai Imilab Technology Co.,Ltd",
    "fe90": "JUMA",
    "fe8f": "CSR",
    "fe8e": "ARM Ltd",
    "fe8d": "Interaxon Inc."
};

module.exports.companyNames = companyNames;