var companyNames = {
    "feff": "GN Netcom",
    "fefe": "GN ReSound A/S",
    "fefd": "Gimbal, Inc.",
    "fefc": "Gimbal, Inc.",
    "fefb": "Stollmann E+V GmbH",
    "fefa": "PayPal, Inc.",
    "fef9": "PayPal, Inc.",
    "fef8": "Aplix Corporation",
    "fef7": "Aplix Corporation",
    "fef6": "Wicentric, Inc.",
    "fef5": "Dialog Semiconductor GmbH",
    "fef4": "Google",
    "fef3": "Google",
    "fef2": "CSR",
    "fef1": "CSR",
    "fef0": "Intel",
    "feef": "Polar Electro Oy",
    "feee": "Polar Electro Oy",
    "feed": "Tile, Inc.",
    "feec": "Tile, Inc.",
    "feeb": "Swirl Networks, Inc.",
    "feea": "Swirl Networks, Inc.",
    "fedb": "Perka, Inc.",
    "feda": "ISSC Technologies Corporation",
    "fed9": "Pebble Technology Corporation",
    "fed8": "Google",
    "fee9": "Quintic Corp.",
    "fee8": "Quintic Corp.",
    "fee7": "Tencent Holdings Limited",
    "fee6": "Seed Labs, Inc.",
    "fee5": "Nordic Semiconductor ASA",
    "fee4": "Nordic Semiconductor ASA",
    "fee3": "Anki, Inc.",
    "fee2": "Anki, Inc.",
    "fee1": "Anhui Huami Information Technology Co.",
    "fee0": "Anhui Huami Information Technology Co.",
    "fedf": "Design SHIFT",
    "fede": "Coin, Inc.",
    "fedd": "Jawbone",
    "fedc": "Jawbone",
    "fed7": "Broadcom Corporation",
    "fed6": "Broadcom Corporation",
    "fed5": "Plantronics Inc.",
    "fed4": "Apple, Inc.",
    "fed3": "Apple, Inc.",
    "fed2": "Apple, Inc.",
    "fed1": "Apple, Inc.",
    "fed0": "Apple, Inc.",
    "fecf": "Apple, Inc.",
    "fece": "Apple, Inc.",
    "fecd": "Apple, Inc.",
    "fecc": "Apple, Inc.",
    "fecb": "Apple, Inc.",
    "feca": "Apple, Inc.",
    "fec9": "Apple, Inc.",
    "fec8": "Apple, Inc.",
    "fec7": "Apple, Inc.",
    "fec6": "Kocomojo, LLC",
    "fec5": "Realtek Semiconductor Corp.",
    "fec4": "PLUS Location Systems",
    "fec3": "360fly, Inc.",
    "fec2": "Blue Spark Technologies, Inc.",
    "fec1": "KDDI Corporation",
    "fec0": "KDDI Corporation",
    "febf": "Nod, Inc.",
    "febe": "Bose Corporation",
    "febd": "Clover Network, Inc.",
    "febc": "Dexcom, Inc.",
    "febb": "adafruit industries",
    "feba": "Tencent Holdings Limited",
    "feb9": "LG Electronics",
    "feb8": "Facebook, Inc.",
    "feb7": "Facebook, Inc.",
    "feb6": "Vencer Co, Ltd",
    "feb5": "WiSilica Inc.",
    "feb4": "WiSilica Inc.",
    "feb3": "Taobao",
    "feb2": "Microsoft Corporation",
    "feb1": "Electronics Tomorrow Limited",
    "feb0": "Nest Labs Inc.",
    "feaf": "Nest Labs Inc.",
    "feae": "Nokia Corporation",
    "fead": "Nokia Corporation",
    "feac": "Nokia Corporation",
    "feab": "Nokia Corporation",
    "feaa": "Google",
    "fea9": "Savant Systems LLC",
    "fea8": "Savant Systems LLC",
    "fea7": "UTC Fire and Security",
    "fea6": "GoPro, Inc.",
    "fea5": "GoPro, Inc.",
    "fea4": "Paxton Access Ltd",
    "fea3": "ITT Industries",
    "fea2": "Intrepid Control Systems, Inc.",
    "fea1": "Intrepid Control Systems, Inc.",
    "fea0": "Google",
    "fe9f": "Google",
    "fe9e": "Dialog Semiconductor B.V.",
    "fe9d": "Mobiquity Networks Inc",
    "fe9c": "GSI Laboratories, Inc.",
    "fe9b": "Samsara Networks, Inc",
    "fe9a": "Estimote",
    "fe99": "Currant, Inc.",
    "fe98": "Currant, Inc.",
    "fe97": "Tesla Motor Inc.",
    "fe96": "Tesla Motor Inc.",
    "fe95": "Xiaomi Inc.",
    "fe94": "OttoQ Inc.",
    "fe93": "OttoQ Inc.",
    "fe92": "Jarden Safety & Security",
    "fe91": "Shanghai Imilab Technology Co.,Ltd",
    "fe90": "JUMA",
    "fe8f": "CSR",
    "fe8e": "ARM Ltd",
    "fe8d": "Interaxon Inc.",
    "fe8c": "TRON Forum",
    "fe8b": "Apple, Inc.",
    "fe8a": "Apple, Inc.",
    "fe89": "B&) Play A/S",
    "fe88": "SALTO SYSTEMS S.L.",
    "fe87": "Qingdao Yeelink Information Technology Co., Ltd.",
    "fe86": "​HUAWEI Technologies Co., Ltd",
    "fe85": "RF Digital Corp",
    "fe84": "RF Digital Corp",
    "fe83": "Blue Bite",
    "fe82": "Medtronic Inc.",
    "fe81": "Medtronic Inc.",
    "fe80": "Doppler Lab",
    "fe7f": "Doppler Lab",
    "fe7e": "Awear Solutions Ltd",
    "fe7d": "Aterica Health Inc.",
    "fe7c": "Stollmann E+V GmbH",
    "fe7b": "Orion Labs, Inc.",
    "fe7a": "Bragi GmbH",
    "fe79": "Zebra Technologies",
    "fe78": "Hewlett-Packard Company",
    "fe77": "Hewlett-Packard Company",
    "fe76": "TangoMe",
    "fe75": "TangoMe",
    "fe74": "unwire",
    "fe73": "St. Jude Medical, Inc.",
    "fe72": "St. Jude Medical, Inc.",
    "fe71": "Plume Design Inc",
    "fe70": "Beijing Jingdong Century Trading Co., Ltd.",
    "fe6f": "LINE Corporation",
    "fe6e": "The University of Tokyo",
    "fe6d": "The Universtiy of Tokyo",
    "fe6c": "TASER International, Inc.",
    "fe6b": "TASER International, Inc.",
    "fe6a": "Kontakt Micro-Location Sp. z o.o",
    "fe69": "Qualcomm Life Inc",
    "fe68": "Qualcomm Life Inc",
    "fe67": "Lab Sensor Solutions",
    "fe66": "Intel Corporation",
    "fe65": "CHIPOLO d.o.o.",
    "fe64": "Siemens AG",
    "fe63": "Connected Yard, Inc.",
    "fe62": "Indagem Tech LLC",
    "fe61": "Logitech International SA",
    "fe60": "Lierda Science & Technology Group Co., Ltd.",
    "fe5f": "Eyefi, Inc.",
    "fe5e": "Plastc Corporation",
    "fe5d": "Grundfos A/S",
    "fe5c": "million hunters GmbH",
    "fe5b": "GT-tronics HK Ltd",
    "fe5a": "Chronologics Corporation",
    "fe59": "Nordic Semiconductor ASA",
    "fe58": "Nordic Semiconductor ASA",
    "fe57": "Dotted Labs",
    "fe56": "Google Inc.",
    "fe55": "Google Inc.",
    "fe54": "Motiv, Inc.",
    "fe53": "3M",
    "fe52": "Setpoint Medical",
    "fe51": "SRAM",
    "fe50": "Google Inc.",
    "fe4f": "Molekule, Inc.",
    "fe4e": "NTT docomo",
    "fe4d": "Casambi Technologies Oy",
    "fe4c": "Volkswagen AG",
    "fe4b": "Koninklijke Philips N.V.",
    "fe4a": "OMRON HEALTHCARE Co., Ltd.",
    "fe49": "SenionLab AB",
    "fe48": "General Motors",
    "fe47": "General Motors",
    "fe46": "B&O Play AS",
    "fe45": "Snapchat Inc",
    "fe44": "SK Telecom",
    "fe43": "Andreas Stihl AG & Co. KG",
    "fe42": "Nets A/S",
    "fe41": "Inugo Systems Limited",
    "fe40": "Inugo Systems Limited",
    "fe3f": "Friday Labs Limited",
    "fe3e": "BD Medical",
    "fe3d": "BD Medical",
    "fe3c": "Alibaba",
    "fe3b": "Dolby Laboratories",
    "fe3a": "TTS Tooltechnic Systems AG & Co. KG",
    "fe39": "TTS Tooltechnic Systems AG & Co. KG",
    "fe38": "Spaceek LTD",
    "fe37": "Spaceek LTD",
    "fe36": "HUAWEI Technologies Co., Ltd",
    "fe35": "HUAWEI Technologies Co., Ltd",
    "fe34": "SmallLoop LLC",
    "fe33": "CHIPOLO d.o.o.",
    "fe32": "Pro-Mark, Inc.",
    "fe31": "Volkswagen AG",
    "fe30": "Volkswagen AG",
    "fe2f": "CRESCO Wireless, Inc",
    "fe2e": "ERi,Inc.",
    "fe2d": "SMART INNOVATION Co.,Ltd",
    "fe2c": "Google Inc.",
    "fe2b": "ITT Industries",
    "fe2a": "DaisyWorks, Inc.",
    "fe29": "Gibson Innovations",
    "fe28": "Ayla Networks",
    "fe27": "Google Inc.",
    "fe26": "Google Inc.",
    "fe25": "Apple, Inc.",
    "fe24": "August Home Inc",
    "fe23": "Zoll Medical Corporation",
    "fe22": "Zoll Medical Corporation",
    "fe21": "Bose Corporation",
    "fe20": "Emerson",
    "fe1f": "Garmin International, Inc.",
    "fe1e": "Smart Innovations Co., Ltd",
    "fe1d": "Illuminati Instrument Corporation",
    "fe1c": "NetMedia, Inc.",
    "fe1b": "Tyto Life LLC",
    "fe1a": "Tyto Life LLC",
    "fe19": "Google Inc.",
    "fe18": "Runtime, Inc.",
    "fe17": "Telit Wireless Solutions GmbH",
    "fe16": "Footmarks, Inc.",
    "fe15": "Amazon Fulfillment Services, Inc.",
    "fe14": "Flextronics International USA Inc.",
    "fe13": "Apple Inc.",
    "fe12": "M-Way Solutions GmbH",
    "fe11": "GMC-I Messtechnik GmbH",
    "fe10": "Lapis Semiconductor Co., Ltd.",
    "fe0f": "Philips Lighting B.V.",
    "fe0e": "Setec Pty Ltd",
    "fe0d": "Procter & Gamble",
    "fe0c": "Procter & Gamble",
    "fe0b": "Ruwido Austria GmbH",
    "fe0a": "Ruwido Austria GmbH",
    "fe09": "Pillsy, Inc.",
    "fe08": "Microsoft",
    "fe07": "Sonos Inc.",
    "fe06": "Qualcomm Technologies, Inc.",
    "fe05": "CORE Transport Technologies NZ Limited",
    "fe04": "OpenPath Security Inc",
    "fe03": "Amazon Fulfillment Services, Inc",
    "fe02": "Robert Bosch GmbH",
    "fe01": "Duracell U.S. Operations Inc.",
    "fe00": "Amazon Fulfillment Services Inc.",
    "fdff": "OSRAM GmbH",
    "fdfe": "ADHERIUM(NZ) LIMITED",
    "fdfd": "RecursiveSoft Inc.",
    "fdfc": "Optrel AG",
    "fdfb": "Tandem Diabetes Care",
    "fdfa": "Tandem Diabetes Care",
    "fdf9": "INIA",
    "fdf8": "Onvocal",
    "fdf7": "HP Inc.",
    "fdf6": "AIAIAI ApS",
    "fdf5": "Milwaukee Electric Tools",
    "fdf4": "O. E. M. Controls, Inc.",
    "fdf3": "Amersports",
    "fdf2": "AMICCOM Electronics Corporation",
    "fdf1": "LAMPLIGHT Co.,Ltd",
    "fdf0": "Google Inc.",
    "fdef": "ART AND PROGRAM, INC.",
    "fdee": "Huawei Technologies Co., Ltd.",
    "fded": "Pole Star",
    "fdec": "Mannkind Corporation",
    "fdeb": "Syntronix Corporation",
    "fdea": "SeeScan, Inc",
    "fde9": "Spacesaver Corporation",
    "fde8": "Robert Bosch GmbH",
    "fde7": "SECOM Co., LTD",
    "fde6": "Intelletto Technologies Inc",
    "fde5": "SMK Corporation",
    "fde4": "JUUL Labs, Inc.",
    "fde3": "Abbott Diabetes Care",
    "fde2": "Google Inc.",
    "fde1": "Fortin Electronic Systems",
    "fde0": "John Deere"
};

module.exports.companyNames = companyNames;
